### ISSUE TITLE
Washington DC bug

### ISSUE THREAD

**Issue by swd-turner** [IMMM-SFA/gamut#26]
DC can't be plotted currently due to inconsistency between mapping file state name ("D.C.") and CONUS shape file ("DC").

**Comment by KristianNelson** [comment]
Can we just make an edit to the mapping file and change it from D.C. to DC? or will that conflict with other files?

**Comment by swd-turner** [comment]
I can't quite remember. Either way, this is a minor issue affecting only the visualization I think... if you can fix in a few minutes then go for it, otherwise press on with the more important work of expanding the teleconnection counts. We can return to this later.

**Comment by KristianNelson** [comment]
For reference next week. This can be fixed by: 

```
city_watershed_mapping$city_state <- gsub("D.C.", "DC", city_watershed_mapping$city_state)
```
