### ISSUE TITLE
Jackson MS fix

### ISSUE THREAD

**Issue by swd-turner** [IMMM-SFA/gamut#90]
Jackson MS needs a fix on the runoff data to update for the key watershed (now 3743, not 3683). This is addressed currently with a temporary fix in `count_watershed_data.R`

**Comment by KristianNelson** [comment]
Does this mean we need to run the PIC function again in order to get the new runoff calculation? Since it is currently using the older watershed shape.

**Comment by swd-turner** [comment]
Yea, if you run Jackson MS you'll find it fails because it can't grab a runoff time series associated with the new key watershed. My temporary fix has been to revert to the old watershed for the runoff only (which is a reasonable assumption). This issue is not urgent but something we should address along with issue #85 I reckon
